### ISSUE TITLE
Feature request: way to override _user_agent

### ISSUE THREAD

**Issue by plicease** [trwyant/perl-Test-Pod-LinkCheck-Lite#1]
This would allow using a HTTP::Tiny subclass that caches responses, very useful for a dist that has lots of external links.

**Comment by trwyant** [comment]
Thanks for the suggestion, and I apologize profusely for letting this lie fallow for so long. I hope to look into it next week.

**Comment by trwyant** [comment]
Refreshing myself on the internals, I have a couple questions:

- This package is supposed to cache responses itself unless the `cache_url_response` argument to `new()` is explicitly set false. Are you finding that this does not work?
- If you still want this, how about a `user_agent` argument to `new()`, which would be required to be a subclass of `HTTP::Tiny`, but might be either an object or a class name. A `user_agent()` accessor method would return the object (even if the argument was a class name).  The default value of `agent` would have to come from this, and maybe `agent` should be deprecated in favor of `agent_string` and eventually removed.

**Comment by plicease** [comment]
> * This package is supposed to cache responses itself unless the `cache_url_response` argument to `new()` is explicitly set false. Are you finding that this does not work?

Right I believe that I did have that turned on as it is the default and for a single run it caches in memory (I believe), but I wanted subsequent runs of the test to be fast as well, and by cacheing to disk I was able to get a test for a dist with a large number of links to take seconds instead of minutes.  I was able to do this by monkey patching and forcing the use of my own HTTP::Tiny subclass, but of course I would prefer an officially supported interface.

> * If you still want this, how about a `user_agent` argument to `new()`, which would be required to be a subclass of `HTTP::Tiny`, but might be either an object or a class name. A `user_agent()` accessor method would return the object (even if the argument was a class name).  The default value of `agent` would have to come from this, and maybe `agent` should be deprecated in favor of `agent_string` and eventually removed.

Yup.  That would be perfect.  There may be other applications for this interface as well.

**Comment by trwyant** [comment]
Understood. I suppose a **complete** implementation of this package would include on-disk caching, but right now I want to get you straight. It occurs to me that my implementation needs to include freezing _user_agent() (or at least, its interface contract) for a while, to give you (and anyone else who has done the same hack) time to make the transition to the supported interface.

**Comment by plicease** [comment]
My feeling is that if I am using an undocumented feature like `_user_agent()` I am knowingly using something that could break at anytime.  But it is up to you for how long you want to support that :)

**Comment by trwyant** [comment]
Just pushed my attempt to address your issue. Please let me know if it meets your needs.

**Comment by plicease** [comment]
👍🏻 I have verified that my script works correctly as-is, and also by modifying it to use the new interface.  In both cases it correctly caches the results.  Please if you can ping me when this is available in CPAN I will update my scripts and require the new version.

**Comment by trwyant** [comment]
Thank you. I have it on my calendar to put out a test version tomorrow, followed by a production version on the 14th if nothing bad turns up.

**Comment by trwyant** [comment]
Just sent Test-Pod-LinkCheck-Lite 0.010_01 to PAUSE. Please let me know if there are any problems. If none show up in a week, I will make a production release.

**Comment by trwyant** [comment]
The production release (0.011) went to PAUSE a couple days ago. I will close this issue in a week if nothing further comes up.
