### ISSUE TITLE
Checking https links and modules from CPAN Meta DB requires IO::Socket::SSL and Net::SSLeay

### ISSUE THREAD

**Issue by mjgardner** [trwyant/perl-Test-Pod-LinkCheck-Lite#2]
Per [HTTP::Tiny's docs](https://perldoc.perl.org/HTTP::Tiny#SSL-SUPPORT), this module should recommend or require the installation of IO::Socket::SSL and Net::SSLeay, and perhaps skip CPAN Meta DB checks if they're not installed

**Comment by trwyant** [comment]
Thank you for this, and I apologize for letting it hang fire for so long. Hope to get to it next week (and the check is in the mail ...)

**Comment by trwyant** [comment]
Just pushed my attempt to address the https: issue. What I have done is:
- Turn https: links into skipped tests if `HTTP::Tiny->can_ssl()` returns false;
- Display a diagnostic on the first such per Test::Pod::LinkCheck::Lite instance;
- Document this in the POD;
- Have the authortest target test without `IO::Socket::SSL` and `Net::SSLeay`.

Please let me know what you think.

**Comment by trwyant** [comment]
Just sent Test-Pod-LinkCheck-Lite 0.010_01 to PAUSE. Please let me know if there are any problems. If none show up in a week, I will make a production release.

**Comment by trwyant** [comment]
The production release (0.011) went to PAUSE a couple days ago. I will close this issue in a week if nothing further comes up.
